# ExerciseType: FILL_IN_BLANKS, MATCH_PAIRS, MULTIPLE_CHOICE, TIMED_CHALLENGE,
# FLASHCARD, SENTENCE_RECONSTRUCTION, LISTENING, AI_CONTEXTUAL.
# AttemptResult (CORRECT, INCORRECT, SKIPPED). DifficultyLevel.
